### ISSUE TITLE
Generated model does not include Nullable

### ISSUE THREAD

**Issue by redbaty** [ralmsdeveloper/EntityFrameworkCore.FirebirdSQL#10]
### The issue

From database to code the generated models does not include the nullable types

### Steps to reproduce

Create a table with a nullable column, and scaffold-it

### Error details

```
Exception message: An exception occurred while reading a database value for property 'Dglob210.Codagenda'. The expected type was 'System.Int32' but the actual value was null.
Stack trace:    at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.TryReadValue[TValue](ValueBuffer valueBuffer, Int32 index, IPropertyBase property)
   at lambda_method(Closure , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   at WebApplication1.Startup.ConfigureServices(IServiceCollection services) in C:\Users\desenv09\source\repos\WebApplication1\WebApplication1\Startup.cs:line 35
```

### Further technical details

Firebird version: 2.15
EntityFrameworkCore.FirebirdSql version: 2.0.9

**Comment by ralmsdeveloper** [comment]
@redbaty , I'll check that out today.

**Comment by ralmsdeveloper** [comment]
@redbaty, you can use the preview version 2.0.10-preview 1 to solve this, until version 2.10 is released

Thanks!

**Comment by redbaty** [comment]
@ralmsdeveloper Are you sure its fixed ? At least in my model it still doesnt use nullables.

I'm using

`Scaffold-DbContext "User=SYSDBA;Password=masterkey;Database=E:\SGE32\Dados\EMPRESA001.FDB;DataSource=127.0.0.1;Port=3050;Dialect=3;Charset=NONE;Role=;Connection lifetime=15;Pooling=true;MinPoolSize=0;MaxPoolSize=50;Packet Size=8192;ServerType=0;" "EntityFrameworkCore.FirebirdSql" -OutputDir Entities -Context "MaisDbContext" -force -verbose`

**Comment by ralmsdeveloper** [comment]
Olá @redbaty, pelo que tinha visto, o problema estava em seu Startup(então imaginei que era no Migrate), por que isso tinha acontecido em uma versão anterior, sabendo que o caso é no Scaffolding, estarei analisando agora.

Sim, Brasileiro! 😄

**Comment by redbaty** [comment]
@ralmsdeveloper Eu coloquei no startup só pra fazer teste mesmo 😄 . Mas é revigorante um respositório tão importante mantido por um brasileiro, parabéns! 🎉

**Comment by ralmsdeveloper** [comment]
@redbaty você poderia disponibilizar seu banco de testes? para que possa fazer um teste e simular a sua situação, em meus testes eu tive exito, em seu caso está aparecendo o IsRequired no context?

é sabido que irá aparecer apenas quando o campo for obrigatório correto!

**Comment by redbaty** [comment]
@ralmsdeveloper Não, ta normal sem o IsRequired, mas lá no modelo ta int sem o "?" ou Nullable<int> daí quando vai fazer a conversão dá aquele erro lá. Se você quiser te mando o contexto inteiro.

Column Name	#	Data Type	Charset	Length	Scale	Not Null	Auto Generated	Auto Increment	Default	Key	Description
CODAGENDA	104	INTEGER	[NULL]	10	[NULL]	false	false	false	0	false	[NULL]

**Comment by ralmsdeveloper** [comment]
Tudo bem resolvi isso, favor verificar o 2.0.10-preview2

```csharp
public partial class Blog
{
    public Blog()
    {
        Book = new HashSet<Book>();
    }

    public int BlogId { get; set; }
    [StringLength(100)]
    public string Descricao { get; set; }
    public int? IntIsNullable { get; set; }
    public byte[] TestBytes { get; set; }
    public DateTime TestDate { get; set; }
    [Column(TypeName = "DECIMAL(18, 2)")]
    public decimal TestDecimal { get; set; }
    public double TestDouble { get; set; }
    public Guid TestGuid { get; set; }
    public int TestInt { get; set; }
    [Column("decimalIsNullable", TypeName = "DECIMAL(18, 2)")]
    public decimal? DecimalIsNullable { get; set; }

    [InverseProperty("Blog")]
    public ICollection<Book> Book { get; set; }
}
```

Se ficou resolvido pra você, fique a vontade em fechar o issue!
Obrigado.

**Comment by redbaty** [comment]
@ralmsdeveloper Olá denovo e desculpa o incomodo, agora durante o saffolding deu este erro:

`Dynamic SQL Error
SQL error code = -206
Column unknown
RF.RDB$IDENTITY_TYPE
At line 44, column 17`

**Comment by ralmsdeveloper** [comment]
Isso é por que uso o Firebird 3.0, Mais tenho que deixar isso Compatível com 2.5.
Irei verificar isso!

**Comment by ralmsdeveloper** [comment]
Quero que fique a vontade.
Fiz a implementação, favor verificar preview3.
Obrigado.

**Comment by redbaty** [comment]
@ralmsdeveloper Agora deu este erro:

```System.InvalidOperationException: The property list {'Codigoemp', 'Numloc', 'Codigoemp', 'Numloc'} cannot be used, because it contains a duplicate - 'Codigoemp'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddIndex(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasIndex(Index index, IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasIndex(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasIndex(IReadOnlyList`1 propertyNames, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.HasIndex(String[] propertyNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitIndex(EntityTypeBuilder builder, DatabaseIndex index)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitIndexes(EntityTypeBuilder builder, ICollection`1 indexes)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.CreateFromDatabaseModel(DatabaseModel databaseModel, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ModelScaffolder.Generate(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String projectPath, String outputPath, String rootNamespace, String contextName, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The property list {'Codigoemp', 'Numloc', 'Codigoemp', 'Numloc'} cannot be used, because it contains a duplicate - 'Codigoemp'.```

**Comment by redbaty** [comment]
Pode ser que o erro desta vez esteja na database, mas como não apareceu a tabela ta um pouco dificil de achar hehe

**Comment by ralmsdeveloper** [comment]
Para facilitar meus testes coloca a estrutura da tabela aqui. por que crio um ambiente para simular isso.

**Comment by redbaty** [comment]
@ralmsdeveloper Taí, é bem grande. E mais uma vez: Muito obrigado!

[Squema.zip](https://github.com/ralmsdeveloper/EntityFrameworkCore.FirebirdSQL/files/1419730/Squema.zip)

**Comment by ralmsdeveloper** [comment]
Estou analisando, enquanto analiso, poderia testar com o preview4?

**Comment by redbaty** [comment]
@ralmsdeveloper Tentei, e resultou no mesmo erro:

```System.InvalidOperationException: The property list {'Codigoemp', 'Numloc', 'Codigoemp', 'Numloc'} cannot be used, because it contains a duplicate - 'Codigoemp'.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddIndex(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasIndex(Index index, IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasIndex(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasIndex(IReadOnlyList`1 propertyNames, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.HasIndex(String[] propertyNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitIndex(EntityTypeBuilder builder, DatabaseIndex index)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitIndexes(EntityTypeBuilder builder, ICollection`1 indexes)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.CreateFromDatabaseModel(DatabaseModel databaseModel, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ModelScaffolder.Generate(String connectionString, IEnumerable`1 tables, IEnumerable`1 schemas, String projectPath, String outputPath, String rootNamespace, String contextName, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The property list {'Codigoemp', 'Numloc', 'Codigoemp', 'Numloc'} cannot be used, because it contains a duplicate - 'Codigoemp'.```

**Comment by redbaty** [comment]
@ralmsdeveloper Ah, e se você quiser conversar no slack, ou outro tipo de serviço de mensagem instantânea é até vantagem pra mim, porque o github não me notifica

**Comment by ralmsdeveloper** [comment]
Consegui simular aqui, prefiro por aqui... por que podemos ter um histórico em nossa linha do tempo. 
Até pra saber se progredimos.
Eu consegui simular aqui. já estou fazendo o ajuste!

**Comment by ralmsdeveloper** [comment]
Olá @redbaty, subi para o nuget a preview5 se certifique que tudo ocorrerá bem!

Percebo que em seu banco existe varias tabelas sem chave primária essas serão descartadas pelo scaffolding.

**Comment by redbaty** [comment]
Olá @ralmsdeveloper tem mesmo, esse banco é muito antigo e já foi portado varias vezes, inclusive este é o intuído do uso, dá uma limpada nisso aí.
Mas deu ecrto sim muito obrigado!

Ah e um bug tão pequeno que eu acho que nem precisa de abrir outro issue:

No contexto gerado ta faltando o 

`using EntityFrameworkCore.FirebirdSql.Extensions;`
